# -*- coding: utf-8 -*-
"""tp3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17EzU2zEK3sCYd3suUMM6iEwczAqLA0ag

**Ejercicio 1.** Se desea conocer el rendimiento de un estudiante al rendir un examen teniendo
en cuenta la cantidad de horas de estudio por semana, las calificaciones obtenidas previamente
y el porcentaje de asistencia a las clases.
1. Dividir aleatoriamente el conjunto de datos para utilizar una parte de los mismos como
conjunto de entrenamiento (el 80 %) y otro como conjunto de prueba (el 20 %).
2. Hallar la ecuación del modelo de regresión lineal mútiple y calcular el coeficiente de determinación R2.
3. Hallar la ecuación del modelo de regresión lineal loística, construir la matriz de confusión para el conjunto de prueba y calcular el valor de accuracy y el F1-score. (Este modelo puede construirse con bibliotecas específicas.)
4. Utilizar cada uno de los modelos hallados para predecir la calificación obtenida y la condición de aprobación de un estudiante que le dedicó 25 horas de estudio a la semana,
que asistió un 58 % a las clases y obtuvo una calificación de 68 puntos en exámenes previos.
"""

import pandas as pd
import numpy as np
from sklearn import svm
from sklearn.linear_model import LogisticRegression

#########  Métricas TP1 ##########
# Reutilizamos las funciones de métricas que definimos en el TP1 para evaluar el
# desempeño de los modelos de clasificación (regresión logística y SVM) en el
# conjunto de prueba. Clase positiva: 'APROBADO'.
def calcularPositivosYnegativos(predicciones, esperados):
  TP = 0
  FP = 0
  TN = 0
  FN = 0
  # Recorremos el vector de predicciones y comparamos el resultado con el esperado
  for i in range(len(predicciones)):
      pred = str(predicciones[i]).strip().lower()
      esp = str(esperados[i]).strip().lower()
      if pred == 'aprobado':   # Predicciones POSITIVAS
        if esp == 'aprobado':
          TP += 1
        else:
          FP += 1
      else:                               # Predicciones NEGATIVAS
        if esp == 'reprobado':
          TN += 1
        else:
          FN += 1
  return TP,FP,TN,FN


# Matriz de confusión para un conjunto de predicciones y esperados
def matrizDeConfusion(predicciones, esperados):
  tp, fp, tn, fn = calcularPositivosYnegativos(predicciones, esperados)
  return [[tp, fn], [fp, tn]]

def accuracy(tp, fp, tn, fn):
  return (tp + tn) / (tp + tn + fp + fn)

def recall(tp, fn):
  # Si no hay positivos reales (tp+fn=0), el recall no está definido: se toma 0.
  if tp + fn == 0:
    return 0
  return tp / (tp + fn)

def especificidad(fp, tn):
  if tn + fp == 0:
    return 0
  return tn / (tn + fp)

def precision(tp, fp):
  # Ocurre, por ejemplo, con el kernel sigmoideo, que puede predecir TODOS los
  # casos como negativos (0 positivos predichos) y dejaría tp=fp=0.
  if tp + fp == 0:
    return 0
  return tp / (tp + fp)

def f1_score(tp, fp, fn):
  p = precision(tp, fp)
  r = recall(tp, fn)
  if p + r == 0:
    return 0
  return 2 * (p * r) / (p + r)

def tpr_fpr(tp, fp, tn, fn):
  return tp / (tp + fn), fp / (tn + fp)

def falsePositiveRate(fp, tn):
  if tn + fp == 0:
    return 0
  return fp / (tn + fp)


#### 1. Dividir aleatoriamente el conjunto de datos para utilizar una parte de los mismos como conjunto de entrenamiento (el 80 %)  ####
#### y otro como conjunto de prueba (el 20 %).                                                                                      ####
# Cargar archivo csv
try:
    df = pd.read_csv('Estudiantes.csv', encoding='utf-8')
except UnicodeDecodeError:
    df = pd.read_csv('Estudiantes.csv', encoding='latin-1')

# Identificar el nombre exacto de la columna de Calificación
target_col = 'Calificación' if 'Calificación' in df.columns else 'Calificacion'

# Seleccionar las variables independientes (X) y la variable dependiente (y)
X_data = np.array(df[['Horas de estudio por semana', 'Porcentaje de asistencia', 'Calificaciones previas']])
X = np.hstack([np.ones((X_data.shape[0], 1)), X_data])

tamanio_entrenamiento = int(len(X) * 0.8)

X_entrenamiento_calif = X[:tamanio_entrenamiento]
X_prueba_calif = X[tamanio_entrenamiento:]

X_entrenamiento_cond = X_data[:tamanio_entrenamiento] 
X_prueba_cond = X_data[tamanio_entrenamiento:]

y_prueba_cond = np.array(df['Condición'])[tamanio_entrenamiento:]
y_entrenamiento_cond = np.array(df['Condición'])[:tamanio_entrenamiento]

y = np.array(df[target_col])
y_entrenamiento = y[:tamanio_entrenamiento]
y_prueba = y[tamanio_entrenamiento:]


#### 2. Hallar la ecuación del modelo de regresión lineal múltiple y calcular el coeficiente de determinación R^2 ####
def calcularCoheficientesBeta(X, y):
    # Calcula los coeficientes beta utilizando la fórmula de mínimos cuadrados.
    # Fórmula: beta = (X^T * X)^(-1) * X^T * y
    return np.linalg.inv(X.T @ X) @ X.T @ y

# Calcular los coeficientes beta
beta = calcularCoheficientesBeta(X_entrenamiento_calif, y_entrenamiento)
print(f"### REGRESIÓN LINEAL ###")
print()
print(f"Coeficientes beta: {beta}")
print(f"x1 = Horas de estudio por semana")
print(f"x2 = Porcentaje de asistencia")
print(f"x3 = Calificaciones previas")
print(f"Ecuación del modelo: y = {beta[0]:.6f} + {beta[1]:.6f}*x1 + {beta[2]:.6f}*x2 + {beta[3]:.6f}*x3")
print()

def predecirRendimiento(entrada):
    # Predecir el rendimiento del estudiante utilizando los coeficientes beta calculados.
    # Se construye un vector de características con un 1 para el término independiente.
    return entrada @ beta

for i in range(10):
    entrada = X_prueba_calif[i]
    prediccion = predecirRendimiento(entrada)
    print(f"Predicción para el estudiante {i + 1}: {prediccion:.2f}, Valor real: {y_prueba[i]:.2f}")

print()
y_pred = np.array([predecirRendimiento(entrada) for entrada in X_prueba_calif])

def sst(y):
    # Calcula la suma total de cuadrados (SST) para evaluar la variabilidad total en los datos.
    return np.sum((y - np.mean(y)) ** 2)

def ssr(y, y_pred):
    # Calcula la suma de cuadrados de regresión (SSR) para evaluar la variabilidad explicada por el modelo.
    return np.sum((y_pred - np.mean(y)) ** 2)

def sse(y, y_pred):
    # Calcula la suma de cuadrados del error (SSE) para evaluar la variabilidad no explicada por el modelo.
    return np.sum((y - y_pred) ** 2)

def calcularR2(y, y_pred):
    # Calcula el coeficiente de determinación R^2, que indica la proporción de la variabilidad total explicada por el modelo.
    return ssr(y, y_pred) / sst(y)

r2 = calcularR2(y_prueba, y_pred)
print(f"Coeficiente de determinación R^2: {r2}")
print()

#### Ejercicio 1 - Punto 3 ####
modelo_logistico = LogisticRegression()
modelo_logistico.fit(X_entrenamiento_cond, y_entrenamiento_cond) 

beta0_log = modelo_logistico.intercept_[0]
beta_log = modelo_logistico.coef_[0]
print(f"Coeficientes: beta0 = {beta0_log:.6f}, beta1 = {beta_log[0]:.6f}, "
      f"beta2 = {beta_log[1]:.6f}, beta3 = {beta_log[2]:.6f}")
print(f"p(x) = exp(z) / (1 + exp(z)),  con z = {beta0_log:.6f} "
      f"+ {beta_log[0]:.6f}*x1 + {beta_log[1]:.6f}*x2 + {beta_log[2]:.6f}*x3")
print()

y_pred_log = modelo_logistico.predict(X_prueba_cond) 

tp_log, fp_log, tn_log, fn_log = calcularPositivosYnegativos(y_pred_log, y_prueba_cond)
matriz_confusion_log = matrizDeConfusion(y_pred_log, y_prueba_cond)
accuracy_log = accuracy(tp_log, fp_log, tn_log, fn_log)
f1_log = f1_score(tp_log, fp_log, fn_log)


print("Matriz de confusión (regresión logística):")
print(matriz_confusion_log)
print(f"Accuracy: {accuracy_log:.4f}")
print(f"F1-score: {f1_log:.4f}")


#### Ejercicio 1 - Punto 4 ####
#### Predicción para un estudiante con 25 hs de estudio, 58% asistencia y 68 de calificación previa ####
print("### PREDICCIÓN PARA NUEVO ESTUDIANTE (Ejercicio 1, punto 4) ###")
print()
nuevo_estudiante = np.array([25, 58, 68])  # x1=horas, x2=asistencia, x3=calif. previa

# Con el modelo de regresión lineal (se antepone el 1 para el término independiente)
nuevo_estudiante_lineal = np.hstack([1, nuevo_estudiante])
prediccion_calificacion = predecirRendimiento(nuevo_estudiante_lineal)
print(f"Regresión lineal → Calificación estimada: {prediccion_calificacion:.2f}")

# Con el modelo de regresión logística. Se busca el índice de 'Aprobado' dentro de
# modelo_logistico.classes_ para leer la probabilidad correcta (sklearn ordena las
# clases alfabéticamente, no necesariamente en el orden que uno espera).
indice_aprobado = list(modelo_logistico.classes_).index('Aprobado')
prob_aprobado = modelo_logistico.predict_proba(nuevo_estudiante.reshape(1, -1))[0][indice_aprobado]
condicion = modelo_logistico.predict(nuevo_estudiante.reshape(1, -1))[0]
print(f"Regresión logística → Probabilidad de aprobar: {prob_aprobado:.4f} "
      f"→ Condición: {condicion}")
print()

"""**Ejercicio 2.** Utilizando los mismos conjuntos de entrenamiento y de prueba que en el Ejercicio 1., se pide lo siguiente.
1. Aplicar el método de SVM para clasificar los ejemplos del conjunto de prueba, utilizando
diferentes kernels y diferentes valores del parámetro C, costo de violación de restricción.
(Este punto puede realizarse con bibliotecas específicas.)
2. Para cada uno de los modelos construidos en el inciso anterior, calcular la matriz de
confusión para el conjunto de prueba, el valor de accuracy y el F1-score.
"""

import pandas as pd
import numpy as np
from sklearn import svm
from sklearn.linear_model import LogisticRegression

#########  Métricas TP1 ##########
# Reutilizamos las funciones de métricas que definimos en el TP1 para evaluar el
# desempeño de los modelos de clasificación (regresión logística y SVM) en el
# conjunto de prueba. Clase positiva: 'APROBADO'.
def calcularPositivosYnegativos(predicciones, esperados):
  TP = 0
  FP = 0
  TN = 0
  FN = 0
  # Recorremos el vector de predicciones y comparamos el resultado con el esperado
  for i in range(len(predicciones)):
      pred = str(predicciones[i]).strip().lower()
      esp = str(esperados[i]).strip().lower()
      if pred == 'aprobado':   # Predicciones POSITIVAS
        if esp == 'aprobado':
          TP += 1
        else:
          FP += 1
      else:                               # Predicciones NEGATIVAS
        if esp == 'reprobado':
          TN += 1
        else:
          FN += 1
  return TP,FP,TN,FN


# Matriz de confusión para un conjunto de predicciones y esperados
def matrizDeConfusion(predicciones, esperados):
  tp, fp, tn, fn = calcularPositivosYnegativos(predicciones, esperados)
  return [[tp, fn], [fp, tn]]

def accuracy(tp, fp, tn, fn):
  return (tp + tn) / (tp + tn + fp + fn)

def recall(tp, fn):
  # Si no hay positivos reales (tp+fn=0), el recall no está definido: se toma 0.
  if tp + fn == 0:
    return 0
  return tp / (tp + fn)

def especificidad(fp, tn):
  if tn + fp == 0:
    return 0
  return tn / (tn + fp)

def precision(tp, fp):
  # Ocurre, por ejemplo, con el kernel sigmoideo, que puede predecir TODOS los
  # casos como negativos (0 positivos predichos) y dejaría tp=fp=0.
  if tp + fp == 0:
    return 0
  return tp / (tp + fp)

def f1_score(tp, fp, fn):
  p = precision(tp, fp)
  r = recall(tp, fn)
  if p + r == 0:
    return 0
  return 2 * (p * r) / (p + r)

def tpr_fpr(tp, fp, tn, fn):
  return tp / (tp + fn), fp / (tn + fp)

#### Ejercicio 2 ####
#### 1. Aplicar el método de SVM para clasificar los ejemplos del conjunto de prueba, utilizando    ####
#### diferentes kernels y diferentes valores del parámetro C, costo de violación de restricción.    ####
#### (Este punto puede realizarse con bibliotecas específicas.)                                     ####

kernels = ['linear', 'poly', 'rbf', 'sigmoid'] # Diferentes kernels a utilizar en los modelos SVM
valores_C = [0.1, 1.0, 10.0] # Diferentes valores del parámetro C a utilizar en los modelos SVM

resultados_svm = [] # Se almacenarán los resultados de cada modelo SVM

for kernel in kernels:
    for C in valores_C:
        modelo_svm = svm.SVC(kernel=kernel, C=C) # Se crea el modelo SVM con el kernel y valor de C especificados
        modelo_svm.fit(X_entrenamiento_cond, y_entrenamiento_cond)  # Se entrena el modelo con los datos de entrenamiento
        y_pred_svm = modelo_svm.predict(X_prueba_cond)  # Se realizan las predicciones sobre el conjunto de prueba

        #### Ejercicio 2 - Punto 2 ####
        #### Matriz de confusión, accuracy y F1-score para cada modelo ####
        tp_svm, fp_svm, tn_svm, fn_svm = calcularPositivosYnegativos(y_pred_svm, y_prueba_cond) # Se calculan los valores de TP, FP, TN y FN para el modelo SVM
        matriz_confusion_svm = matrizDeConfusion(y_pred_svm, y_prueba_cond) # Se construye la matriz de confusión para el modelo SVM
        accuracy_svm = accuracy(tp_svm, fp_svm, tn_svm, fn_svm)# Se calcula el valor de accuracy para el modelo SVM
        f1_svm = f1_score(tp_svm, fp_svm, fn_svm)# Se calcula el valor de F1-score para el modelo SVM

        resultados_svm.append({ # Se almacenan los resultados del modelo SVM
            'kernel': kernel,
            'C': C,
            'accuracy': accuracy_svm,
            'f1_score': f1_svm,
            'matriz_confusion': matriz_confusion_svm
        })

        print(f"--- Kernel: {kernel} | C: {C} ---") 
        for i in range(min(10, len(X_prueba_calif))): 
            print(f"  Predicción SVM para el estudiante {i + 1}: {y_pred_svm[i]}, "
                  f"Valor real: {y_prueba_cond[i]}")
        print(f"  Matriz de confusión:\n{matriz_confusion_svm}")
        print(f"  Accuracy: {accuracy_svm:.4f}")
        print(f"  F1-score: {f1_svm:.4f}")
        print()

"""**Ejercicio 3.** ¿Cuál de todos los métodos implementados en este trabajo se recomienda utilizar
para predecir si un estudiante aprobará el examen o no? Justificar la respuesta.
"""

print("### EJERCICIO 3: COMPARACIÓN DE MODELOS DE CLASIFICACIÓN ###")
print()

print(f"{'Modelo':<25}{'Accuracy':<12}{'F1-score':<12}")
print(f"{'Regresión logística':<25}{accuracy_log:<12.4f}{f1_log:<12.4f}")
mejor_svm = max(resultados_svm, key=lambda r: r['f1_score'])
for r in resultados_svm:
    nombre = f"SVM ({r['kernel']}, C={r['C']})"
    print(f"{nombre:<25}{r['accuracy']:<12.4f}{r['f1_score']:<12.4f}")

"""### EJERCICIO 3: COMPARACIÓN DE MODELOS DE CLASIFICACIÓN ###

Modelo                   Accuracy    F1-score    
Regresión logística      0.7535      0.7586      
SVM (linear, C=0.1)      0.7465      0.7534      
SVM (linear, C=1.0)      0.7535      0.7619      
SVM (linear, C=10.0)     0.7535      0.7619      
SVM (poly, C=0.1)        0.7535      0.7552      
SVM (poly, C=1.0)        0.7606      0.7639      
SVM (poly, C=10.0)       0.7606      0.7671      
SVM (rbf, C=0.1)         0.7676      0.7755      
SVM (rbf, C=1.0)         0.7465      0.7600      
SVM (rbf, C=10.0)        0.7746      0.7949      
SVM (sigmoid, C=0.1)     0.3169      0.0202      
SVM (sigmoid, C=1.0)     0.3169      0.0202      
SVM (sigmoid, C=10.0)    0.3169      0.0202
"""